services:
  trial-buddy:
    restart: always
    env_file:
      - .env
    environment:

      ENVIRONMENT: ${ENVIRONMENT}

      DATABASE_URI: ${DATABASE_URI}
      DATABASE_URI_LOCAL: ${DATABASE_URI_LOCAL}

      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_BASE_URL: ${PAYPAL_BASE_URL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      TOKEN_ALGORITHM: ${TOKEN_ALGORITHM}

      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
      SECRET_KEY_EMAIL: ${SECRET_KEY_EMAIL}
      ALGORITHM_EMAIL: ${ALGORITHM_EMAIL}


    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8001:8080